//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PISI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORD
    {
        public int Word_ID { get; set; }
        public string Word_English { get; set; }
        public string Word_IPA { get; set; }
        public string Word_Vietnamese { get; set; }
        public string Word_SoundSimilar { get; set; }
        public string Word_UrlImage { get; set; }
        public string Word_UrlSound { get; set; }
    }
}
